### ISSUE TITLE
Alterar comportamento do link 'Contato'

### ISSUE THREAD

**Issue by zedsousa** [zedsousa/promoxama_landingpage#5]
Atualmente ao clicar em contato, o usuário está sendo redirecionado para o topo da página, mas ele deve ser redirecionado para a área de contato.
![image](https://github.com/zedsousa/promoxama_landingpage/assets/39315413/992aa7c0-a9f4-4a9b-ad4d-02c79a43b9fa)

**Comment by italosilva01** [comment]
Qual é a área de contato ?
